web:
  image: sanqiu/mage2-docker
  container_name: mage-web
  environment:
    - APACHE_RUN_USER=www-data
    - APACHE_RUN_GROUP=www-data
    - APACHE_PID_FILE=/var/run/apache2/apache2.pid
    - APACHE_RUN_DIR=/var/run/apache2
    - APACHE_LOG_DIR=/var/log/apache2
    - APACHE_LOCK_DIR=/var/lock/apache2
  expose:
   - "80"
  ports:
   - "80:80"
  links:
   - db:mysql
  entrypoint: ["/usr/sbin/apache2"]
  command: ["-D", "FOREGROUND"]

db:
  image: mysql
  container_name: mage-db
  environment:
    - MYSQL_ROOT_PASSWORD="root"
    - MYSQL_DATABASE="magento2"
    - MYSQL_USER="admin"
    - MYSQL_PASSWORD="abc456123"
